declare const styles: {
  readonly page: string;
  readonly header: string;
  readonly title: string;
  readonly subtitle: string;
  readonly stats: string;
  readonly statCard: string;
  readonly statIcon: string;
  readonly statBody: string;
  readonly statLabel: string;
  readonly statValue: string;
  readonly tableWrap: string;
  readonly table: string;
  readonly th: string;
  readonly emptyRow: string;
  readonly emptyText: string;
  readonly emptySubtext: string;
  readonly tableFoot: string;
  readonly modalBody: string;
  readonly modalActions: string;
};
export default styles;
