declare const styles: {
  readonly page: string;
  readonly card: string;
  readonly logo: string;
  readonly heading: string;
  readonly subheading: string;
  readonly form: string;
  readonly field: string;
  readonly label: string;
  readonly input: string;
  readonly inputError: string;
  readonly pwWrap: string;
  readonly eyeBtn: string;
  readonly top: string;
  readonly iconWrap: string;
  readonly title: string;
  readonly sub: string;
  readonly errorBanner: string;
  readonly hint: string;
};
export default styles;
