declare const styles: {
  readonly page: string;
  readonly pageHeader: string;
  readonly pageTitle: string;
  readonly pageSub: string;
  readonly header: string;
  readonly title: string;
  readonly subtitle: string;
  readonly stats: string;
  readonly statCard: string;
  readonly statIcon: string;
  readonly statBody: string;
  readonly statValue: string;
  readonly statLabel: string;
  readonly tableCard: string;
  readonly tableHeader: string;
  readonly tableTitle: string;
  readonly tableSearch: string;
  readonly thead: string;
  readonly table: string;
  readonly th: string;
  readonly empty: string;
  readonly emptyText: string;
  readonly modal: string;
  readonly modalText: string;
  readonly modalActions: string;
};
export default styles;
