declare const styles: {
  readonly page: string;
  readonly hero: string;
  readonly heroTitle: string;
  readonly heroSub: string;
  readonly controls: string;
  readonly searchWrap: string;
  readonly searchIcon: string;
  readonly searchInput: string;
  readonly filterSelect: string;
  readonly grid: string;
  readonly emptyState: string;
  readonly emptyText: string;
  readonly emptySubtext: string;
  readonly categories: string;
  readonly catBtn: string;
  readonly catActive: string;
  readonly emptySub: string;
  readonly count: string;
};
export default styles;
